2014/01/18 21:11:07 - Error while retrieving btc_eur trade history
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/btcebot/bot.py", line 41, in _runBot
    trades = btceapi.getTradeHistory(p, conn)
  File "/Library/Python/2.7/site-packages/btceapi/public.py", line 111, in getTradeHistory
    history = connection.makeJSONRequest("/api/2/%s/trades" % pair)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 118, in makeJSONRequest
    response = self.makeRequest(url, extra_headers, params)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 113, in makeRequest
    response = self.conn.getresponse().read()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1045, in getresponse
    response.begin()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 409, in begin
    version, status, reason = self._read_status()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 373, in _read_status
    raise BadStatusLine(line)
BadStatusLine: ''

--------------------------------------------------------------------------------
2014/01/18 21:11:07 - Error while retrieving btc_rur trade history
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/btcebot/bot.py", line 41, in _runBot
    trades = btceapi.getTradeHistory(p, conn)
  File "/Library/Python/2.7/site-packages/btceapi/public.py", line 111, in getTradeHistory
    history = connection.makeJSONRequest("/api/2/%s/trades" % pair)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 118, in makeJSONRequest
    response = self.makeRequest(url, extra_headers, params)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 112, in makeRequest
    self.conn.request("POST", url, params, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 973, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1001, in _send_request
    self.putrequest(method, url, **skips)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 871, in putrequest
    raise CannotSendRequest()
CannotSendRequest

--------------------------------------------------------------------------------
2014/01/18 21:14:42 - Error while retrieving ltc_usd ticker
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/btcebot/bot.py", line 100, in _ticker_loop
    response = btceapi.getTicker(p, conn)
  File "/Library/Python/2.7/site-packages/btceapi/public.py", line 50, in getTicker
    response = connection.makeJSONRequest("/api/2/%s/ticker" % pair)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 118, in makeJSONRequest
    response = self.makeRequest(url, extra_headers, params)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 113, in makeRequest
    response = self.conn.getresponse().read()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1045, in getresponse
    response.begin()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 409, in begin
    version, status, reason = self._read_status()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 373, in _read_status
    raise BadStatusLine(line)
BadStatusLine: ''

--------------------------------------------------------------------------------
2014/01/18 21:14:42 - Error while retrieving btc_eur ticker
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/btcebot/bot.py", line 100, in _ticker_loop
    response = btceapi.getTicker(p, conn)
  File "/Library/Python/2.7/site-packages/btceapi/public.py", line 50, in getTicker
    response = connection.makeJSONRequest("/api/2/%s/ticker" % pair)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 118, in makeJSONRequest
    response = self.makeRequest(url, extra_headers, params)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 112, in makeRequest
    self.conn.request("POST", url, params, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 973, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1001, in _send_request
    self.putrequest(method, url, **skips)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 871, in putrequest
    raise CannotSendRequest()
CannotSendRequest

--------------------------------------------------------------------------------
2014/01/18 21:14:42 - Error while retrieving btc_rur ticker
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/btcebot/bot.py", line 100, in _ticker_loop
    response = btceapi.getTicker(p, conn)
  File "/Library/Python/2.7/site-packages/btceapi/public.py", line 50, in getTicker
    response = connection.makeJSONRequest("/api/2/%s/ticker" % pair)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 118, in makeJSONRequest
    response = self.makeRequest(url, extra_headers, params)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 112, in makeRequest
    self.conn.request("POST", url, params, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 973, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1001, in _send_request
    self.putrequest(method, url, **skips)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 871, in putrequest
    raise CannotSendRequest()
CannotSendRequest

--------------------------------------------------------------------------------
2014/01/18 21:14:43 - Error while retrieving btc_eur depth
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/btcebot/bot.py", line 28, in _runBot
    asks, bids = btceapi.getDepth(p, conn)
  File "/Library/Python/2.7/site-packages/btceapi/public.py", line 67, in getDepth
    depth = connection.makeJSONRequest("/api/2/%s/depth" % pair)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 118, in makeJSONRequest
    response = self.makeRequest(url, extra_headers, params)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 113, in makeRequest
    response = self.conn.getresponse().read()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1045, in getresponse
    response.begin()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 409, in begin
    version, status, reason = self._read_status()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 373, in _read_status
    raise BadStatusLine(line)
BadStatusLine: ''

--------------------------------------------------------------------------------
2014/01/18 21:14:43 - Error while retrieving btc_rur depth
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/btcebot/bot.py", line 28, in _runBot
    asks, bids = btceapi.getDepth(p, conn)
  File "/Library/Python/2.7/site-packages/btceapi/public.py", line 67, in getDepth
    depth = connection.makeJSONRequest("/api/2/%s/depth" % pair)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 118, in makeJSONRequest
    response = self.makeRequest(url, extra_headers, params)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 112, in makeRequest
    self.conn.request("POST", url, params, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 973, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1001, in _send_request
    self.putrequest(method, url, **skips)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 871, in putrequest
    raise CannotSendRequest()
CannotSendRequest

--------------------------------------------------------------------------------
2014/01/18 21:14:43 - Error while retrieving ltc_eur trade history
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/btcebot/bot.py", line 41, in _runBot
    trades = btceapi.getTradeHistory(p, conn)
  File "/Library/Python/2.7/site-packages/btceapi/public.py", line 111, in getTradeHistory
    history = connection.makeJSONRequest("/api/2/%s/trades" % pair)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 118, in makeJSONRequest
    response = self.makeRequest(url, extra_headers, params)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 112, in makeRequest
    self.conn.request("POST", url, params, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 973, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1001, in _send_request
    self.putrequest(method, url, **skips)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 871, in putrequest
    raise CannotSendRequest()
CannotSendRequest

--------------------------------------------------------------------------------
2014/01/18 21:14:43 - Error while retrieving btc_usd trade history
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/btcebot/bot.py", line 41, in _runBot
    trades = btceapi.getTradeHistory(p, conn)
  File "/Library/Python/2.7/site-packages/btceapi/public.py", line 111, in getTradeHistory
    history = connection.makeJSONRequest("/api/2/%s/trades" % pair)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 118, in makeJSONRequest
    response = self.makeRequest(url, extra_headers, params)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 112, in makeRequest
    self.conn.request("POST", url, params, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 973, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1001, in _send_request
    self.putrequest(method, url, **skips)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 871, in putrequest
    raise CannotSendRequest()
CannotSendRequest

--------------------------------------------------------------------------------
2014/01/18 21:14:43 - Error while retrieving ltc_btc trade history
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/btcebot/bot.py", line 41, in _runBot
    trades = btceapi.getTradeHistory(p, conn)
  File "/Library/Python/2.7/site-packages/btceapi/public.py", line 111, in getTradeHistory
    history = connection.makeJSONRequest("/api/2/%s/trades" % pair)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 118, in makeJSONRequest
    response = self.makeRequest(url, extra_headers, params)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 112, in makeRequest
    self.conn.request("POST", url, params, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 973, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1001, in _send_request
    self.putrequest(method, url, **skips)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 871, in putrequest
    raise CannotSendRequest()
CannotSendRequest

--------------------------------------------------------------------------------
2014/01/18 21:14:43 - Error while retrieving ltc_rur trade history
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/btcebot/bot.py", line 41, in _runBot
    trades = btceapi.getTradeHistory(p, conn)
  File "/Library/Python/2.7/site-packages/btceapi/public.py", line 111, in getTradeHistory
    history = connection.makeJSONRequest("/api/2/%s/trades" % pair)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 118, in makeJSONRequest
    response = self.makeRequest(url, extra_headers, params)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 112, in makeRequest
    self.conn.request("POST", url, params, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 973, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1001, in _send_request
    self.putrequest(method, url, **skips)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 871, in putrequest
    raise CannotSendRequest()
CannotSendRequest

--------------------------------------------------------------------------------
2014/01/18 21:14:43 - Error while retrieving ltc_usd trade history
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/btcebot/bot.py", line 41, in _runBot
    trades = btceapi.getTradeHistory(p, conn)
  File "/Library/Python/2.7/site-packages/btceapi/public.py", line 111, in getTradeHistory
    history = connection.makeJSONRequest("/api/2/%s/trades" % pair)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 118, in makeJSONRequest
    response = self.makeRequest(url, extra_headers, params)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 112, in makeRequest
    self.conn.request("POST", url, params, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 973, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1001, in _send_request
    self.putrequest(method, url, **skips)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 871, in putrequest
    raise CannotSendRequest()
CannotSendRequest

--------------------------------------------------------------------------------
2014/01/18 21:14:43 - Error while retrieving btc_eur trade history
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/btcebot/bot.py", line 41, in _runBot
    trades = btceapi.getTradeHistory(p, conn)
  File "/Library/Python/2.7/site-packages/btceapi/public.py", line 111, in getTradeHistory
    history = connection.makeJSONRequest("/api/2/%s/trades" % pair)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 118, in makeJSONRequest
    response = self.makeRequest(url, extra_headers, params)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 112, in makeRequest
    self.conn.request("POST", url, params, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 973, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1001, in _send_request
    self.putrequest(method, url, **skips)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 871, in putrequest
    raise CannotSendRequest()
CannotSendRequest

--------------------------------------------------------------------------------
2014/01/18 21:14:43 - Error while retrieving btc_rur trade history
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/btcebot/bot.py", line 41, in _runBot
    trades = btceapi.getTradeHistory(p, conn)
  File "/Library/Python/2.7/site-packages/btceapi/public.py", line 111, in getTradeHistory
    history = connection.makeJSONRequest("/api/2/%s/trades" % pair)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 118, in makeJSONRequest
    response = self.makeRequest(url, extra_headers, params)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 112, in makeRequest
    self.conn.request("POST", url, params, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 973, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1001, in _send_request
    self.putrequest(method, url, **skips)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 871, in putrequest
    raise CannotSendRequest()
CannotSendRequest

--------------------------------------------------------------------------------
2014/01/18 21:20:37 - Error while retrieving ltc_rur ticker
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/btcebot/bot.py", line 100, in _ticker_loop
    response = btceapi.getTicker(p, conn)
  File "/Library/Python/2.7/site-packages/btceapi/public.py", line 50, in getTicker
    response = connection.makeJSONRequest("/api/2/%s/ticker" % pair)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 118, in makeJSONRequest
    response = self.makeRequest(url, extra_headers, params)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 113, in makeRequest
    response = self.conn.getresponse().read()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1045, in getresponse
    response.begin()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 409, in begin
    version, status, reason = self._read_status()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 373, in _read_status
    raise BadStatusLine(line)
BadStatusLine: ''

--------------------------------------------------------------------------------
2014/01/18 21:20:37 - Error while retrieving ltc_usd ticker
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/btcebot/bot.py", line 100, in _ticker_loop
    response = btceapi.getTicker(p, conn)
  File "/Library/Python/2.7/site-packages/btceapi/public.py", line 50, in getTicker
    response = connection.makeJSONRequest("/api/2/%s/ticker" % pair)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 118, in makeJSONRequest
    response = self.makeRequest(url, extra_headers, params)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 112, in makeRequest
    self.conn.request("POST", url, params, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 973, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1001, in _send_request
    self.putrequest(method, url, **skips)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 871, in putrequest
    raise CannotSendRequest()
CannotSendRequest

--------------------------------------------------------------------------------
2014/01/18 21:20:37 - Error while retrieving btc_eur ticker
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/btcebot/bot.py", line 100, in _ticker_loop
    response = btceapi.getTicker(p, conn)
  File "/Library/Python/2.7/site-packages/btceapi/public.py", line 50, in getTicker
    response = connection.makeJSONRequest("/api/2/%s/ticker" % pair)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 118, in makeJSONRequest
    response = self.makeRequest(url, extra_headers, params)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 112, in makeRequest
    self.conn.request("POST", url, params, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 973, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1001, in _send_request
    self.putrequest(method, url, **skips)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 871, in putrequest
    raise CannotSendRequest()
CannotSendRequest

--------------------------------------------------------------------------------
2014/01/18 21:20:37 - Error while retrieving btc_rur ticker
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/btcebot/bot.py", line 100, in _ticker_loop
    response = btceapi.getTicker(p, conn)
  File "/Library/Python/2.7/site-packages/btceapi/public.py", line 50, in getTicker
    response = connection.makeJSONRequest("/api/2/%s/ticker" % pair)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 118, in makeJSONRequest
    response = self.makeRequest(url, extra_headers, params)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 112, in makeRequest
    self.conn.request("POST", url, params, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 973, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1001, in _send_request
    self.putrequest(method, url, **skips)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 871, in putrequest
    raise CannotSendRequest()
CannotSendRequest

--------------------------------------------------------------------------------
2014/01/18 21:27:30 - Error while retrieving btc_usd ticker
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/btcebot/bot.py", line 100, in _ticker_loop
    response = btceapi.getTicker(p, conn)
  File "/Library/Python/2.7/site-packages/btceapi/public.py", line 50, in getTicker
    response = connection.makeJSONRequest("/api/2/%s/ticker" % pair)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 118, in makeJSONRequest
    response = self.makeRequest(url, extra_headers, params)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 113, in makeRequest
    response = self.conn.getresponse().read()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1045, in getresponse
    response.begin()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 409, in begin
    version, status, reason = self._read_status()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 373, in _read_status
    raise BadStatusLine(line)
BadStatusLine: ''

--------------------------------------------------------------------------------
2014/01/18 21:27:30 - Error while retrieving ltc_btc ticker
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/btcebot/bot.py", line 100, in _ticker_loop
    response = btceapi.getTicker(p, conn)
  File "/Library/Python/2.7/site-packages/btceapi/public.py", line 50, in getTicker
    response = connection.makeJSONRequest("/api/2/%s/ticker" % pair)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 118, in makeJSONRequest
    response = self.makeRequest(url, extra_headers, params)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 112, in makeRequest
    self.conn.request("POST", url, params, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 973, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1001, in _send_request
    self.putrequest(method, url, **skips)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 871, in putrequest
    raise CannotSendRequest()
CannotSendRequest

--------------------------------------------------------------------------------
2014/01/18 21:27:30 - Error while retrieving ltc_rur ticker
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/btcebot/bot.py", line 100, in _ticker_loop
    response = btceapi.getTicker(p, conn)
  File "/Library/Python/2.7/site-packages/btceapi/public.py", line 50, in getTicker
    response = connection.makeJSONRequest("/api/2/%s/ticker" % pair)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 118, in makeJSONRequest
    response = self.makeRequest(url, extra_headers, params)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 112, in makeRequest
    self.conn.request("POST", url, params, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 973, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1001, in _send_request
    self.putrequest(method, url, **skips)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 871, in putrequest
    raise CannotSendRequest()
CannotSendRequest

--------------------------------------------------------------------------------
2014/01/18 21:27:30 - Error while retrieving ltc_usd ticker
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/btcebot/bot.py", line 100, in _ticker_loop
    response = btceapi.getTicker(p, conn)
  File "/Library/Python/2.7/site-packages/btceapi/public.py", line 50, in getTicker
    response = connection.makeJSONRequest("/api/2/%s/ticker" % pair)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 118, in makeJSONRequest
    response = self.makeRequest(url, extra_headers, params)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 112, in makeRequest
    self.conn.request("POST", url, params, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 973, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1001, in _send_request
    self.putrequest(method, url, **skips)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 871, in putrequest
    raise CannotSendRequest()
CannotSendRequest

--------------------------------------------------------------------------------
2014/01/18 21:27:30 - Error while retrieving btc_eur ticker
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/btcebot/bot.py", line 100, in _ticker_loop
    response = btceapi.getTicker(p, conn)
  File "/Library/Python/2.7/site-packages/btceapi/public.py", line 50, in getTicker
    response = connection.makeJSONRequest("/api/2/%s/ticker" % pair)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 118, in makeJSONRequest
    response = self.makeRequest(url, extra_headers, params)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 112, in makeRequest
    self.conn.request("POST", url, params, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 973, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1001, in _send_request
    self.putrequest(method, url, **skips)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 871, in putrequest
    raise CannotSendRequest()
CannotSendRequest

--------------------------------------------------------------------------------
2014/01/18 21:27:30 - Error while retrieving btc_rur ticker
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/btcebot/bot.py", line 100, in _ticker_loop
    response = btceapi.getTicker(p, conn)
  File "/Library/Python/2.7/site-packages/btceapi/public.py", line 50, in getTicker
    response = connection.makeJSONRequest("/api/2/%s/ticker" % pair)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 118, in makeJSONRequest
    response = self.makeRequest(url, extra_headers, params)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 112, in makeRequest
    self.conn.request("POST", url, params, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 973, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1001, in _send_request
    self.putrequest(method, url, **skips)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 871, in putrequest
    raise CannotSendRequest()
CannotSendRequest

--------------------------------------------------------------------------------
2014/01/18 21:32:24 - Error while retrieving ltc_rur ticker
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/btcebot/bot.py", line 100, in _ticker_loop
    response = btceapi.getTicker(p, conn)
  File "/Library/Python/2.7/site-packages/btceapi/public.py", line 50, in getTicker
    response = connection.makeJSONRequest("/api/2/%s/ticker" % pair)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 118, in makeJSONRequest
    response = self.makeRequest(url, extra_headers, params)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 113, in makeRequest
    response = self.conn.getresponse().read()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1045, in getresponse
    response.begin()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 409, in begin
    version, status, reason = self._read_status()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 373, in _read_status
    raise BadStatusLine(line)
BadStatusLine: ''

--------------------------------------------------------------------------------
2014/01/18 21:32:24 - Error while retrieving ltc_usd ticker
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/btcebot/bot.py", line 100, in _ticker_loop
    response = btceapi.getTicker(p, conn)
  File "/Library/Python/2.7/site-packages/btceapi/public.py", line 50, in getTicker
    response = connection.makeJSONRequest("/api/2/%s/ticker" % pair)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 118, in makeJSONRequest
    response = self.makeRequest(url, extra_headers, params)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 112, in makeRequest
    self.conn.request("POST", url, params, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 973, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1001, in _send_request
    self.putrequest(method, url, **skips)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 871, in putrequest
    raise CannotSendRequest()
CannotSendRequest

--------------------------------------------------------------------------------
2014/01/18 21:32:24 - Error while retrieving btc_eur ticker
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/btcebot/bot.py", line 100, in _ticker_loop
    response = btceapi.getTicker(p, conn)
  File "/Library/Python/2.7/site-packages/btceapi/public.py", line 50, in getTicker
    response = connection.makeJSONRequest("/api/2/%s/ticker" % pair)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 118, in makeJSONRequest
    response = self.makeRequest(url, extra_headers, params)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 112, in makeRequest
    self.conn.request("POST", url, params, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 973, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1001, in _send_request
    self.putrequest(method, url, **skips)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 871, in putrequest
    raise CannotSendRequest()
CannotSendRequest

--------------------------------------------------------------------------------
2014/01/18 21:32:24 - Error while retrieving btc_rur ticker
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/btcebot/bot.py", line 100, in _ticker_loop
    response = btceapi.getTicker(p, conn)
  File "/Library/Python/2.7/site-packages/btceapi/public.py", line 50, in getTicker
    response = connection.makeJSONRequest("/api/2/%s/ticker" % pair)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 118, in makeJSONRequest
    response = self.makeRequest(url, extra_headers, params)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 112, in makeRequest
    self.conn.request("POST", url, params, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 973, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1001, in _send_request
    self.putrequest(method, url, **skips)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 871, in putrequest
    raise CannotSendRequest()
CannotSendRequest

--------------------------------------------------------------------------------
2014/01/19 13:03:01 - Error while retrieving ltc_eur ticker
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/btcebot/bot.py", line 100, in _ticker_loop
    response = btceapi.getTicker(p, conn)
  File "/Library/Python/2.7/site-packages/btceapi/public.py", line 50, in getTicker
    response = connection.makeJSONRequest("/api/2/%s/ticker" % pair)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 118, in makeJSONRequest
    response = self.makeRequest(url, extra_headers, params)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 112, in makeRequest
    self.conn.request("POST", url, params, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 973, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1007, in _send_request
    self.endheaders(body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 969, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 829, in _send_output
    self.send(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 791, in send
    self.connect()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1172, in connect
    self.timeout, self.source_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 553, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
gaierror: [Errno 8] nodename nor servname provided, or not known

--------------------------------------------------------------------------------
2014/01/19 13:03:01 - Error while retrieving btc_usd ticker
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/btcebot/bot.py", line 100, in _ticker_loop
    response = btceapi.getTicker(p, conn)
  File "/Library/Python/2.7/site-packages/btceapi/public.py", line 50, in getTicker
    response = connection.makeJSONRequest("/api/2/%s/ticker" % pair)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 118, in makeJSONRequest
    response = self.makeRequest(url, extra_headers, params)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 112, in makeRequest
    self.conn.request("POST", url, params, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 973, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1001, in _send_request
    self.putrequest(method, url, **skips)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 871, in putrequest
    raise CannotSendRequest()
CannotSendRequest

--------------------------------------------------------------------------------
2014/01/19 13:03:01 - Error while retrieving ltc_btc ticker
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/btcebot/bot.py", line 100, in _ticker_loop
    response = btceapi.getTicker(p, conn)
  File "/Library/Python/2.7/site-packages/btceapi/public.py", line 50, in getTicker
    response = connection.makeJSONRequest("/api/2/%s/ticker" % pair)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 118, in makeJSONRequest
    response = self.makeRequest(url, extra_headers, params)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 112, in makeRequest
    self.conn.request("POST", url, params, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 973, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1001, in _send_request
    self.putrequest(method, url, **skips)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 871, in putrequest
    raise CannotSendRequest()
CannotSendRequest

--------------------------------------------------------------------------------
2014/01/19 13:03:01 - Error while retrieving ltc_rur ticker
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/btcebot/bot.py", line 100, in _ticker_loop
    response = btceapi.getTicker(p, conn)
  File "/Library/Python/2.7/site-packages/btceapi/public.py", line 50, in getTicker
    response = connection.makeJSONRequest("/api/2/%s/ticker" % pair)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 118, in makeJSONRequest
    response = self.makeRequest(url, extra_headers, params)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 112, in makeRequest
    self.conn.request("POST", url, params, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 973, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1001, in _send_request
    self.putrequest(method, url, **skips)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 871, in putrequest
    raise CannotSendRequest()
CannotSendRequest

--------------------------------------------------------------------------------
2014/01/19 13:03:01 - Error while retrieving ltc_usd ticker
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/btcebot/bot.py", line 100, in _ticker_loop
    response = btceapi.getTicker(p, conn)
  File "/Library/Python/2.7/site-packages/btceapi/public.py", line 50, in getTicker
    response = connection.makeJSONRequest("/api/2/%s/ticker" % pair)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 118, in makeJSONRequest
    response = self.makeRequest(url, extra_headers, params)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 112, in makeRequest
    self.conn.request("POST", url, params, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 973, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1001, in _send_request
    self.putrequest(method, url, **skips)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 871, in putrequest
    raise CannotSendRequest()
CannotSendRequest

--------------------------------------------------------------------------------
2014/01/19 13:03:01 - Error while retrieving btc_eur ticker
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/btcebot/bot.py", line 100, in _ticker_loop
    response = btceapi.getTicker(p, conn)
  File "/Library/Python/2.7/site-packages/btceapi/public.py", line 50, in getTicker
    response = connection.makeJSONRequest("/api/2/%s/ticker" % pair)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 118, in makeJSONRequest
    response = self.makeRequest(url, extra_headers, params)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 112, in makeRequest
    self.conn.request("POST", url, params, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 973, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1001, in _send_request
    self.putrequest(method, url, **skips)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 871, in putrequest
    raise CannotSendRequest()
CannotSendRequest

--------------------------------------------------------------------------------
2014/01/19 13:03:01 - Error while retrieving btc_rur ticker
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/btcebot/bot.py", line 100, in _ticker_loop
    response = btceapi.getTicker(p, conn)
  File "/Library/Python/2.7/site-packages/btceapi/public.py", line 50, in getTicker
    response = connection.makeJSONRequest("/api/2/%s/ticker" % pair)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 118, in makeJSONRequest
    response = self.makeRequest(url, extra_headers, params)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 112, in makeRequest
    self.conn.request("POST", url, params, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 973, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1001, in _send_request
    self.putrequest(method, url, **skips)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 871, in putrequest
    raise CannotSendRequest()
CannotSendRequest

--------------------------------------------------------------------------------
2014/01/19 13:03:01 - Error while retrieving ltc_eur depth
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/btcebot/bot.py", line 28, in _runBot
    asks, bids = btceapi.getDepth(p, conn)
  File "/Library/Python/2.7/site-packages/btceapi/public.py", line 67, in getDepth
    depth = connection.makeJSONRequest("/api/2/%s/depth" % pair)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 118, in makeJSONRequest
    response = self.makeRequest(url, extra_headers, params)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 112, in makeRequest
    self.conn.request("POST", url, params, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 973, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1007, in _send_request
    self.endheaders(body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 969, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 829, in _send_output
    self.send(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 791, in send
    self.connect()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1172, in connect
    self.timeout, self.source_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 553, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
gaierror: [Errno 8] nodename nor servname provided, or not known

--------------------------------------------------------------------------------
2014/01/19 13:03:01 - Error while retrieving btc_usd depth
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/btcebot/bot.py", line 28, in _runBot
    asks, bids = btceapi.getDepth(p, conn)
  File "/Library/Python/2.7/site-packages/btceapi/public.py", line 67, in getDepth
    depth = connection.makeJSONRequest("/api/2/%s/depth" % pair)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 118, in makeJSONRequest
    response = self.makeRequest(url, extra_headers, params)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 112, in makeRequest
    self.conn.request("POST", url, params, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 973, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1001, in _send_request
    self.putrequest(method, url, **skips)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 871, in putrequest
    raise CannotSendRequest()
CannotSendRequest

--------------------------------------------------------------------------------
2014/01/19 13:03:01 - Error while retrieving ltc_btc depth
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/btcebot/bot.py", line 28, in _runBot
    asks, bids = btceapi.getDepth(p, conn)
  File "/Library/Python/2.7/site-packages/btceapi/public.py", line 67, in getDepth
    depth = connection.makeJSONRequest("/api/2/%s/depth" % pair)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 118, in makeJSONRequest
    response = self.makeRequest(url, extra_headers, params)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 112, in makeRequest
    self.conn.request("POST", url, params, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 973, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1001, in _send_request
    self.putrequest(method, url, **skips)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 871, in putrequest
    raise CannotSendRequest()
CannotSendRequest

--------------------------------------------------------------------------------
2014/01/19 13:03:01 - Error while retrieving ltc_rur depth
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/btcebot/bot.py", line 28, in _runBot
    asks, bids = btceapi.getDepth(p, conn)
  File "/Library/Python/2.7/site-packages/btceapi/public.py", line 67, in getDepth
    depth = connection.makeJSONRequest("/api/2/%s/depth" % pair)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 118, in makeJSONRequest
    response = self.makeRequest(url, extra_headers, params)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 112, in makeRequest
    self.conn.request("POST", url, params, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 973, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1001, in _send_request
    self.putrequest(method, url, **skips)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 871, in putrequest
    raise CannotSendRequest()
CannotSendRequest

--------------------------------------------------------------------------------
2014/01/19 13:03:01 - Error while retrieving ltc_usd depth
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/btcebot/bot.py", line 28, in _runBot
    asks, bids = btceapi.getDepth(p, conn)
  File "/Library/Python/2.7/site-packages/btceapi/public.py", line 67, in getDepth
    depth = connection.makeJSONRequest("/api/2/%s/depth" % pair)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 118, in makeJSONRequest
    response = self.makeRequest(url, extra_headers, params)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 112, in makeRequest
    self.conn.request("POST", url, params, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 973, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1001, in _send_request
    self.putrequest(method, url, **skips)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 871, in putrequest
    raise CannotSendRequest()
CannotSendRequest

--------------------------------------------------------------------------------
2014/01/19 13:03:01 - Error while retrieving btc_eur depth
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/btcebot/bot.py", line 28, in _runBot
    asks, bids = btceapi.getDepth(p, conn)
  File "/Library/Python/2.7/site-packages/btceapi/public.py", line 67, in getDepth
    depth = connection.makeJSONRequest("/api/2/%s/depth" % pair)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 118, in makeJSONRequest
    response = self.makeRequest(url, extra_headers, params)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 112, in makeRequest
    self.conn.request("POST", url, params, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 973, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1001, in _send_request
    self.putrequest(method, url, **skips)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 871, in putrequest
    raise CannotSendRequest()
CannotSendRequest

--------------------------------------------------------------------------------
2014/01/19 13:03:01 - Error while retrieving btc_rur depth
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/btcebot/bot.py", line 28, in _runBot
    asks, bids = btceapi.getDepth(p, conn)
  File "/Library/Python/2.7/site-packages/btceapi/public.py", line 67, in getDepth
    depth = connection.makeJSONRequest("/api/2/%s/depth" % pair)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 118, in makeJSONRequest
    response = self.makeRequest(url, extra_headers, params)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 112, in makeRequest
    self.conn.request("POST", url, params, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 973, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1001, in _send_request
    self.putrequest(method, url, **skips)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 871, in putrequest
    raise CannotSendRequest()
CannotSendRequest

--------------------------------------------------------------------------------
2014/01/19 13:03:01 - Error while retrieving ltc_eur trade history
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/btcebot/bot.py", line 41, in _runBot
    trades = btceapi.getTradeHistory(p, conn)
  File "/Library/Python/2.7/site-packages/btceapi/public.py", line 111, in getTradeHistory
    history = connection.makeJSONRequest("/api/2/%s/trades" % pair)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 118, in makeJSONRequest
    response = self.makeRequest(url, extra_headers, params)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 112, in makeRequest
    self.conn.request("POST", url, params, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 973, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1001, in _send_request
    self.putrequest(method, url, **skips)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 871, in putrequest
    raise CannotSendRequest()
CannotSendRequest

--------------------------------------------------------------------------------
2014/01/19 13:03:01 - Error while retrieving btc_usd trade history
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/btcebot/bot.py", line 41, in _runBot
    trades = btceapi.getTradeHistory(p, conn)
  File "/Library/Python/2.7/site-packages/btceapi/public.py", line 111, in getTradeHistory
    history = connection.makeJSONRequest("/api/2/%s/trades" % pair)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 118, in makeJSONRequest
    response = self.makeRequest(url, extra_headers, params)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 112, in makeRequest
    self.conn.request("POST", url, params, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 973, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1001, in _send_request
    self.putrequest(method, url, **skips)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 871, in putrequest
    raise CannotSendRequest()
CannotSendRequest

--------------------------------------------------------------------------------
2014/01/19 13:03:01 - Error while retrieving ltc_btc trade history
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/btcebot/bot.py", line 41, in _runBot
    trades = btceapi.getTradeHistory(p, conn)
  File "/Library/Python/2.7/site-packages/btceapi/public.py", line 111, in getTradeHistory
    history = connection.makeJSONRequest("/api/2/%s/trades" % pair)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 118, in makeJSONRequest
    response = self.makeRequest(url, extra_headers, params)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 112, in makeRequest
    self.conn.request("POST", url, params, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 973, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1001, in _send_request
    self.putrequest(method, url, **skips)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 871, in putrequest
    raise CannotSendRequest()
CannotSendRequest

--------------------------------------------------------------------------------
2014/01/19 13:03:01 - Error while retrieving ltc_rur trade history
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/btcebot/bot.py", line 41, in _runBot
    trades = btceapi.getTradeHistory(p, conn)
  File "/Library/Python/2.7/site-packages/btceapi/public.py", line 111, in getTradeHistory
    history = connection.makeJSONRequest("/api/2/%s/trades" % pair)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 118, in makeJSONRequest
    response = self.makeRequest(url, extra_headers, params)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 112, in makeRequest
    self.conn.request("POST", url, params, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 973, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1001, in _send_request
    self.putrequest(method, url, **skips)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 871, in putrequest
    raise CannotSendRequest()
CannotSendRequest

--------------------------------------------------------------------------------
2014/01/19 13:03:01 - Error while retrieving ltc_usd trade history
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/btcebot/bot.py", line 41, in _runBot
    trades = btceapi.getTradeHistory(p, conn)
  File "/Library/Python/2.7/site-packages/btceapi/public.py", line 111, in getTradeHistory
    history = connection.makeJSONRequest("/api/2/%s/trades" % pair)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 118, in makeJSONRequest
    response = self.makeRequest(url, extra_headers, params)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 112, in makeRequest
    self.conn.request("POST", url, params, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 973, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1001, in _send_request
    self.putrequest(method, url, **skips)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 871, in putrequest
    raise CannotSendRequest()
CannotSendRequest

--------------------------------------------------------------------------------
2014/01/19 13:03:01 - Error while retrieving btc_eur trade history
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/btcebot/bot.py", line 41, in _runBot
    trades = btceapi.getTradeHistory(p, conn)
  File "/Library/Python/2.7/site-packages/btceapi/public.py", line 111, in getTradeHistory
    history = connection.makeJSONRequest("/api/2/%s/trades" % pair)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 118, in makeJSONRequest
    response = self.makeRequest(url, extra_headers, params)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 112, in makeRequest
    self.conn.request("POST", url, params, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 973, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1001, in _send_request
    self.putrequest(method, url, **skips)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 871, in putrequest
    raise CannotSendRequest()
CannotSendRequest

--------------------------------------------------------------------------------
2014/01/19 13:03:01 - Error while retrieving btc_rur trade history
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/btcebot/bot.py", line 41, in _runBot
    trades = btceapi.getTradeHistory(p, conn)
  File "/Library/Python/2.7/site-packages/btceapi/public.py", line 111, in getTradeHistory
    history = connection.makeJSONRequest("/api/2/%s/trades" % pair)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 118, in makeJSONRequest
    response = self.makeRequest(url, extra_headers, params)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 112, in makeRequest
    self.conn.request("POST", url, params, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 973, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1001, in _send_request
    self.putrequest(method, url, **skips)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 871, in putrequest
    raise CannotSendRequest()
CannotSendRequest

--------------------------------------------------------------------------------
2014/01/19 15:03:28 - Error while retrieving ltc_eur ticker
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/btcebot/bot.py", line 100, in _ticker_loop
    response = btceapi.getTicker(p, conn)
  File "/Library/Python/2.7/site-packages/btceapi/public.py", line 50, in getTicker
    response = connection.makeJSONRequest("/api/2/%s/ticker" % pair)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 118, in makeJSONRequest
    response = self.makeRequest(url, extra_headers, params)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 112, in makeRequest
    self.conn.request("POST", url, params, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 973, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1007, in _send_request
    self.endheaders(body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 969, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 829, in _send_output
    self.send(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 791, in send
    self.connect()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1172, in connect
    self.timeout, self.source_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 553, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
gaierror: [Errno 8] nodename nor servname provided, or not known

--------------------------------------------------------------------------------
2014/01/19 15:03:28 - Error while retrieving btc_usd ticker
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/btcebot/bot.py", line 100, in _ticker_loop
    response = btceapi.getTicker(p, conn)
  File "/Library/Python/2.7/site-packages/btceapi/public.py", line 50, in getTicker
    response = connection.makeJSONRequest("/api/2/%s/ticker" % pair)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 118, in makeJSONRequest
    response = self.makeRequest(url, extra_headers, params)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 112, in makeRequest
    self.conn.request("POST", url, params, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 973, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1001, in _send_request
    self.putrequest(method, url, **skips)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 871, in putrequest
    raise CannotSendRequest()
CannotSendRequest

--------------------------------------------------------------------------------
2014/01/19 15:03:28 - Error while retrieving ltc_btc ticker
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/btcebot/bot.py", line 100, in _ticker_loop
    response = btceapi.getTicker(p, conn)
  File "/Library/Python/2.7/site-packages/btceapi/public.py", line 50, in getTicker
    response = connection.makeJSONRequest("/api/2/%s/ticker" % pair)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 118, in makeJSONRequest
    response = self.makeRequest(url, extra_headers, params)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 112, in makeRequest
    self.conn.request("POST", url, params, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 973, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1001, in _send_request
    self.putrequest(method, url, **skips)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 871, in putrequest
    raise CannotSendRequest()
CannotSendRequest

--------------------------------------------------------------------------------
2014/01/19 15:03:28 - Error while retrieving ltc_rur ticker
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/btcebot/bot.py", line 100, in _ticker_loop
    response = btceapi.getTicker(p, conn)
  File "/Library/Python/2.7/site-packages/btceapi/public.py", line 50, in getTicker
    response = connection.makeJSONRequest("/api/2/%s/ticker" % pair)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 118, in makeJSONRequest
    response = self.makeRequest(url, extra_headers, params)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 112, in makeRequest
    self.conn.request("POST", url, params, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 973, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1001, in _send_request
    self.putrequest(method, url, **skips)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 871, in putrequest
    raise CannotSendRequest()
CannotSendRequest

--------------------------------------------------------------------------------
2014/01/19 15:03:28 - Error while retrieving ltc_usd ticker
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/btcebot/bot.py", line 100, in _ticker_loop
    response = btceapi.getTicker(p, conn)
  File "/Library/Python/2.7/site-packages/btceapi/public.py", line 50, in getTicker
    response = connection.makeJSONRequest("/api/2/%s/ticker" % pair)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 118, in makeJSONRequest
    response = self.makeRequest(url, extra_headers, params)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 112, in makeRequest
    self.conn.request("POST", url, params, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 973, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1001, in _send_request
    self.putrequest(method, url, **skips)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 871, in putrequest
    raise CannotSendRequest()
CannotSendRequest

--------------------------------------------------------------------------------
2014/01/19 15:03:28 - Error while retrieving btc_eur ticker
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/btcebot/bot.py", line 100, in _ticker_loop
    response = btceapi.getTicker(p, conn)
  File "/Library/Python/2.7/site-packages/btceapi/public.py", line 50, in getTicker
    response = connection.makeJSONRequest("/api/2/%s/ticker" % pair)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 118, in makeJSONRequest
    response = self.makeRequest(url, extra_headers, params)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 112, in makeRequest
    self.conn.request("POST", url, params, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 973, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1001, in _send_request
    self.putrequest(method, url, **skips)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 871, in putrequest
    raise CannotSendRequest()
CannotSendRequest

--------------------------------------------------------------------------------
2014/01/19 15:03:28 - Error while retrieving btc_rur ticker
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/btcebot/bot.py", line 100, in _ticker_loop
    response = btceapi.getTicker(p, conn)
  File "/Library/Python/2.7/site-packages/btceapi/public.py", line 50, in getTicker
    response = connection.makeJSONRequest("/api/2/%s/ticker" % pair)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 118, in makeJSONRequest
    response = self.makeRequest(url, extra_headers, params)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 112, in makeRequest
    self.conn.request("POST", url, params, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 973, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1001, in _send_request
    self.putrequest(method, url, **skips)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 871, in putrequest
    raise CannotSendRequest()
CannotSendRequest

--------------------------------------------------------------------------------
2014/01/19 15:08:18 - Error while retrieving ltc_eur ticker
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/btcebot/bot.py", line 100, in _ticker_loop
    response = btceapi.getTicker(p, conn)
  File "/Library/Python/2.7/site-packages/btceapi/public.py", line 50, in getTicker
    response = connection.makeJSONRequest("/api/2/%s/ticker" % pair)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 118, in makeJSONRequest
    response = self.makeRequest(url, extra_headers, params)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 112, in makeRequest
    self.conn.request("POST", url, params, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 973, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1007, in _send_request
    self.endheaders(body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 969, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 829, in _send_output
    self.send(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 791, in send
    self.connect()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1172, in connect
    self.timeout, self.source_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 553, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
gaierror: [Errno 8] nodename nor servname provided, or not known

--------------------------------------------------------------------------------
2014/01/19 15:08:18 - Error while retrieving btc_usd ticker
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/btcebot/bot.py", line 100, in _ticker_loop
    response = btceapi.getTicker(p, conn)
  File "/Library/Python/2.7/site-packages/btceapi/public.py", line 50, in getTicker
    response = connection.makeJSONRequest("/api/2/%s/ticker" % pair)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 118, in makeJSONRequest
    response = self.makeRequest(url, extra_headers, params)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 112, in makeRequest
    self.conn.request("POST", url, params, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 973, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1001, in _send_request
    self.putrequest(method, url, **skips)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 871, in putrequest
    raise CannotSendRequest()
CannotSendRequest

--------------------------------------------------------------------------------
2014/01/19 15:08:18 - Error while retrieving ltc_btc ticker
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/btcebot/bot.py", line 100, in _ticker_loop
    response = btceapi.getTicker(p, conn)
  File "/Library/Python/2.7/site-packages/btceapi/public.py", line 50, in getTicker
    response = connection.makeJSONRequest("/api/2/%s/ticker" % pair)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 118, in makeJSONRequest
    response = self.makeRequest(url, extra_headers, params)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 112, in makeRequest
    self.conn.request("POST", url, params, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 973, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1001, in _send_request
    self.putrequest(method, url, **skips)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 871, in putrequest
    raise CannotSendRequest()
CannotSendRequest

--------------------------------------------------------------------------------
2014/01/19 15:08:18 - Error while retrieving ltc_rur ticker
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/btcebot/bot.py", line 100, in _ticker_loop
    response = btceapi.getTicker(p, conn)
  File "/Library/Python/2.7/site-packages/btceapi/public.py", line 50, in getTicker
    response = connection.makeJSONRequest("/api/2/%s/ticker" % pair)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 118, in makeJSONRequest
    response = self.makeRequest(url, extra_headers, params)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 112, in makeRequest
    self.conn.request("POST", url, params, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 973, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1001, in _send_request
    self.putrequest(method, url, **skips)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 871, in putrequest
    raise CannotSendRequest()
CannotSendRequest

--------------------------------------------------------------------------------
2014/01/19 15:08:18 - Error while retrieving ltc_usd ticker
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/btcebot/bot.py", line 100, in _ticker_loop
    response = btceapi.getTicker(p, conn)
  File "/Library/Python/2.7/site-packages/btceapi/public.py", line 50, in getTicker
    response = connection.makeJSONRequest("/api/2/%s/ticker" % pair)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 118, in makeJSONRequest
    response = self.makeRequest(url, extra_headers, params)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 112, in makeRequest
    self.conn.request("POST", url, params, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 973, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1001, in _send_request
    self.putrequest(method, url, **skips)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 871, in putrequest
    raise CannotSendRequest()
CannotSendRequest

--------------------------------------------------------------------------------
2014/01/19 15:08:18 - Error while retrieving btc_eur ticker
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/btcebot/bot.py", line 100, in _ticker_loop
    response = btceapi.getTicker(p, conn)
  File "/Library/Python/2.7/site-packages/btceapi/public.py", line 50, in getTicker
    response = connection.makeJSONRequest("/api/2/%s/ticker" % pair)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 118, in makeJSONRequest
    response = self.makeRequest(url, extra_headers, params)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 112, in makeRequest
    self.conn.request("POST", url, params, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 973, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1001, in _send_request
    self.putrequest(method, url, **skips)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 871, in putrequest
    raise CannotSendRequest()
CannotSendRequest

--------------------------------------------------------------------------------
2014/01/19 15:08:18 - Error while retrieving btc_rur ticker
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/btcebot/bot.py", line 100, in _ticker_loop
    response = btceapi.getTicker(p, conn)
  File "/Library/Python/2.7/site-packages/btceapi/public.py", line 50, in getTicker
    response = connection.makeJSONRequest("/api/2/%s/ticker" % pair)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 118, in makeJSONRequest
    response = self.makeRequest(url, extra_headers, params)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 112, in makeRequest
    self.conn.request("POST", url, params, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 973, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1001, in _send_request
    self.putrequest(method, url, **skips)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 871, in putrequest
    raise CannotSendRequest()
CannotSendRequest

--------------------------------------------------------------------------------
2014/01/19 16:09:04 - Error while retrieving ltc_eur ticker
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/btcebot/bot.py", line 100, in _ticker_loop
    response = btceapi.getTicker(p, conn)
  File "/Library/Python/2.7/site-packages/btceapi/public.py", line 50, in getTicker
    response = connection.makeJSONRequest("/api/2/%s/ticker" % pair)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 118, in makeJSONRequest
    response = self.makeRequest(url, extra_headers, params)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 112, in makeRequest
    self.conn.request("POST", url, params, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 973, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1007, in _send_request
    self.endheaders(body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 969, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 829, in _send_output
    self.send(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 791, in send
    self.connect()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1172, in connect
    self.timeout, self.source_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 553, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
gaierror: [Errno 8] nodename nor servname provided, or not known

--------------------------------------------------------------------------------
2014/01/19 16:09:04 - Error while retrieving btc_usd ticker
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/btcebot/bot.py", line 100, in _ticker_loop
    response = btceapi.getTicker(p, conn)
  File "/Library/Python/2.7/site-packages/btceapi/public.py", line 50, in getTicker
    response = connection.makeJSONRequest("/api/2/%s/ticker" % pair)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 118, in makeJSONRequest
    response = self.makeRequest(url, extra_headers, params)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 112, in makeRequest
    self.conn.request("POST", url, params, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 973, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1001, in _send_request
    self.putrequest(method, url, **skips)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 871, in putrequest
    raise CannotSendRequest()
CannotSendRequest

--------------------------------------------------------------------------------
2014/01/19 16:09:04 - Error while retrieving ltc_btc ticker
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/btcebot/bot.py", line 100, in _ticker_loop
    response = btceapi.getTicker(p, conn)
  File "/Library/Python/2.7/site-packages/btceapi/public.py", line 50, in getTicker
    response = connection.makeJSONRequest("/api/2/%s/ticker" % pair)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 118, in makeJSONRequest
    response = self.makeRequest(url, extra_headers, params)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 112, in makeRequest
    self.conn.request("POST", url, params, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 973, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1001, in _send_request
    self.putrequest(method, url, **skips)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 871, in putrequest
    raise CannotSendRequest()
CannotSendRequest

--------------------------------------------------------------------------------
2014/01/19 16:09:04 - Error while retrieving ltc_rur ticker
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/btcebot/bot.py", line 100, in _ticker_loop
    response = btceapi.getTicker(p, conn)
  File "/Library/Python/2.7/site-packages/btceapi/public.py", line 50, in getTicker
    response = connection.makeJSONRequest("/api/2/%s/ticker" % pair)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 118, in makeJSONRequest
    response = self.makeRequest(url, extra_headers, params)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 112, in makeRequest
    self.conn.request("POST", url, params, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 973, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1001, in _send_request
    self.putrequest(method, url, **skips)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 871, in putrequest
    raise CannotSendRequest()
CannotSendRequest

--------------------------------------------------------------------------------
2014/01/19 16:09:04 - Error while retrieving ltc_usd ticker
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/btcebot/bot.py", line 100, in _ticker_loop
    response = btceapi.getTicker(p, conn)
  File "/Library/Python/2.7/site-packages/btceapi/public.py", line 50, in getTicker
    response = connection.makeJSONRequest("/api/2/%s/ticker" % pair)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 118, in makeJSONRequest
    response = self.makeRequest(url, extra_headers, params)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 112, in makeRequest
    self.conn.request("POST", url, params, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 973, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1001, in _send_request
    self.putrequest(method, url, **skips)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 871, in putrequest
    raise CannotSendRequest()
CannotSendRequest

--------------------------------------------------------------------------------
2014/01/19 16:09:04 - Error while retrieving btc_eur ticker
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/btcebot/bot.py", line 100, in _ticker_loop
    response = btceapi.getTicker(p, conn)
  File "/Library/Python/2.7/site-packages/btceapi/public.py", line 50, in getTicker
    response = connection.makeJSONRequest("/api/2/%s/ticker" % pair)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 118, in makeJSONRequest
    response = self.makeRequest(url, extra_headers, params)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 112, in makeRequest
    self.conn.request("POST", url, params, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 973, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1001, in _send_request
    self.putrequest(method, url, **skips)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 871, in putrequest
    raise CannotSendRequest()
CannotSendRequest

--------------------------------------------------------------------------------
2014/01/19 16:09:04 - Error while retrieving btc_rur ticker
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/btcebot/bot.py", line 100, in _ticker_loop
    response = btceapi.getTicker(p, conn)
  File "/Library/Python/2.7/site-packages/btceapi/public.py", line 50, in getTicker
    response = connection.makeJSONRequest("/api/2/%s/ticker" % pair)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 118, in makeJSONRequest
    response = self.makeRequest(url, extra_headers, params)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 112, in makeRequest
    self.conn.request("POST", url, params, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 973, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1001, in _send_request
    self.putrequest(method, url, **skips)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 871, in putrequest
    raise CannotSendRequest()
CannotSendRequest

--------------------------------------------------------------------------------
2014/01/19 17:09:50 - Error while retrieving ltc_eur ticker
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/btcebot/bot.py", line 100, in _ticker_loop
    response = btceapi.getTicker(p, conn)
  File "/Library/Python/2.7/site-packages/btceapi/public.py", line 50, in getTicker
    response = connection.makeJSONRequest("/api/2/%s/ticker" % pair)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 118, in makeJSONRequest
    response = self.makeRequest(url, extra_headers, params)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 112, in makeRequest
    self.conn.request("POST", url, params, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 973, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1007, in _send_request
    self.endheaders(body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 969, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 829, in _send_output
    self.send(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 791, in send
    self.connect()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1172, in connect
    self.timeout, self.source_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 553, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
gaierror: [Errno 8] nodename nor servname provided, or not known

--------------------------------------------------------------------------------
2014/01/19 17:09:50 - Error while retrieving btc_usd ticker
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/btcebot/bot.py", line 100, in _ticker_loop
    response = btceapi.getTicker(p, conn)
  File "/Library/Python/2.7/site-packages/btceapi/public.py", line 50, in getTicker
    response = connection.makeJSONRequest("/api/2/%s/ticker" % pair)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 118, in makeJSONRequest
    response = self.makeRequest(url, extra_headers, params)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 112, in makeRequest
    self.conn.request("POST", url, params, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 973, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1001, in _send_request
    self.putrequest(method, url, **skips)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 871, in putrequest
    raise CannotSendRequest()
CannotSendRequest

--------------------------------------------------------------------------------
2014/01/19 17:09:50 - Error while retrieving ltc_btc ticker
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/btcebot/bot.py", line 100, in _ticker_loop
    response = btceapi.getTicker(p, conn)
  File "/Library/Python/2.7/site-packages/btceapi/public.py", line 50, in getTicker
    response = connection.makeJSONRequest("/api/2/%s/ticker" % pair)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 118, in makeJSONRequest
    response = self.makeRequest(url, extra_headers, params)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 112, in makeRequest
    self.conn.request("POST", url, params, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 973, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1001, in _send_request
    self.putrequest(method, url, **skips)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 871, in putrequest
    raise CannotSendRequest()
CannotSendRequest

--------------------------------------------------------------------------------
2014/01/19 17:09:50 - Error while retrieving ltc_rur ticker
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/btcebot/bot.py", line 100, in _ticker_loop
    response = btceapi.getTicker(p, conn)
  File "/Library/Python/2.7/site-packages/btceapi/public.py", line 50, in getTicker
    response = connection.makeJSONRequest("/api/2/%s/ticker" % pair)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 118, in makeJSONRequest
    response = self.makeRequest(url, extra_headers, params)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 112, in makeRequest
    self.conn.request("POST", url, params, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 973, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1001, in _send_request
    self.putrequest(method, url, **skips)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 871, in putrequest
    raise CannotSendRequest()
CannotSendRequest

--------------------------------------------------------------------------------
2014/01/19 17:09:50 - Error while retrieving ltc_usd ticker
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/btcebot/bot.py", line 100, in _ticker_loop
    response = btceapi.getTicker(p, conn)
  File "/Library/Python/2.7/site-packages/btceapi/public.py", line 50, in getTicker
    response = connection.makeJSONRequest("/api/2/%s/ticker" % pair)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 118, in makeJSONRequest
    response = self.makeRequest(url, extra_headers, params)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 112, in makeRequest
    self.conn.request("POST", url, params, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 973, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1001, in _send_request
    self.putrequest(method, url, **skips)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 871, in putrequest
    raise CannotSendRequest()
CannotSendRequest

--------------------------------------------------------------------------------
2014/01/19 17:09:50 - Error while retrieving btc_eur ticker
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/btcebot/bot.py", line 100, in _ticker_loop
    response = btceapi.getTicker(p, conn)
  File "/Library/Python/2.7/site-packages/btceapi/public.py", line 50, in getTicker
    response = connection.makeJSONRequest("/api/2/%s/ticker" % pair)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 118, in makeJSONRequest
    response = self.makeRequest(url, extra_headers, params)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 112, in makeRequest
    self.conn.request("POST", url, params, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 973, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1001, in _send_request
    self.putrequest(method, url, **skips)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 871, in putrequest
    raise CannotSendRequest()
CannotSendRequest

--------------------------------------------------------------------------------
2014/01/19 17:09:50 - Error while retrieving btc_rur ticker
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/btcebot/bot.py", line 100, in _ticker_loop
    response = btceapi.getTicker(p, conn)
  File "/Library/Python/2.7/site-packages/btceapi/public.py", line 50, in getTicker
    response = connection.makeJSONRequest("/api/2/%s/ticker" % pair)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 118, in makeJSONRequest
    response = self.makeRequest(url, extra_headers, params)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 112, in makeRequest
    self.conn.request("POST", url, params, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 973, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1001, in _send_request
    self.putrequest(method, url, **skips)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 871, in putrequest
    raise CannotSendRequest()
CannotSendRequest

--------------------------------------------------------------------------------
2014/01/19 18:10:36 - Error while retrieving ltc_eur ticker
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/btcebot/bot.py", line 100, in _ticker_loop
    response = btceapi.getTicker(p, conn)
  File "/Library/Python/2.7/site-packages/btceapi/public.py", line 50, in getTicker
    response = connection.makeJSONRequest("/api/2/%s/ticker" % pair)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 118, in makeJSONRequest
    response = self.makeRequest(url, extra_headers, params)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 112, in makeRequest
    self.conn.request("POST", url, params, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 973, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1007, in _send_request
    self.endheaders(body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 969, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 829, in _send_output
    self.send(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 791, in send
    self.connect()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1172, in connect
    self.timeout, self.source_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 553, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
gaierror: [Errno 8] nodename nor servname provided, or not known

--------------------------------------------------------------------------------
2014/01/19 18:10:36 - Error while retrieving btc_usd ticker
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/btcebot/bot.py", line 100, in _ticker_loop
    response = btceapi.getTicker(p, conn)
  File "/Library/Python/2.7/site-packages/btceapi/public.py", line 50, in getTicker
    response = connection.makeJSONRequest("/api/2/%s/ticker" % pair)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 118, in makeJSONRequest
    response = self.makeRequest(url, extra_headers, params)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 112, in makeRequest
    self.conn.request("POST", url, params, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 973, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1001, in _send_request
    self.putrequest(method, url, **skips)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 871, in putrequest
    raise CannotSendRequest()
CannotSendRequest

--------------------------------------------------------------------------------
2014/01/19 18:10:36 - Error while retrieving ltc_btc ticker
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/btcebot/bot.py", line 100, in _ticker_loop
    response = btceapi.getTicker(p, conn)
  File "/Library/Python/2.7/site-packages/btceapi/public.py", line 50, in getTicker
    response = connection.makeJSONRequest("/api/2/%s/ticker" % pair)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 118, in makeJSONRequest
    response = self.makeRequest(url, extra_headers, params)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 112, in makeRequest
    self.conn.request("POST", url, params, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 973, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1001, in _send_request
    self.putrequest(method, url, **skips)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 871, in putrequest
    raise CannotSendRequest()
CannotSendRequest

--------------------------------------------------------------------------------
2014/01/19 18:10:36 - Error while retrieving ltc_rur ticker
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/btcebot/bot.py", line 100, in _ticker_loop
    response = btceapi.getTicker(p, conn)
  File "/Library/Python/2.7/site-packages/btceapi/public.py", line 50, in getTicker
    response = connection.makeJSONRequest("/api/2/%s/ticker" % pair)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 118, in makeJSONRequest
    response = self.makeRequest(url, extra_headers, params)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 112, in makeRequest
    self.conn.request("POST", url, params, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 973, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1001, in _send_request
    self.putrequest(method, url, **skips)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 871, in putrequest
    raise CannotSendRequest()
CannotSendRequest

--------------------------------------------------------------------------------
2014/01/19 18:10:36 - Error while retrieving ltc_usd ticker
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/btcebot/bot.py", line 100, in _ticker_loop
    response = btceapi.getTicker(p, conn)
  File "/Library/Python/2.7/site-packages/btceapi/public.py", line 50, in getTicker
    response = connection.makeJSONRequest("/api/2/%s/ticker" % pair)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 118, in makeJSONRequest
    response = self.makeRequest(url, extra_headers, params)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 112, in makeRequest
    self.conn.request("POST", url, params, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 973, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1001, in _send_request
    self.putrequest(method, url, **skips)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 871, in putrequest
    raise CannotSendRequest()
CannotSendRequest

--------------------------------------------------------------------------------
2014/01/19 18:10:36 - Error while retrieving btc_eur ticker
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/btcebot/bot.py", line 100, in _ticker_loop
    response = btceapi.getTicker(p, conn)
  File "/Library/Python/2.7/site-packages/btceapi/public.py", line 50, in getTicker
    response = connection.makeJSONRequest("/api/2/%s/ticker" % pair)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 118, in makeJSONRequest
    response = self.makeRequest(url, extra_headers, params)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 112, in makeRequest
    self.conn.request("POST", url, params, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 973, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1001, in _send_request
    self.putrequest(method, url, **skips)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 871, in putrequest
    raise CannotSendRequest()
CannotSendRequest

--------------------------------------------------------------------------------
2014/01/19 18:10:36 - Error while retrieving btc_rur ticker
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/btcebot/bot.py", line 100, in _ticker_loop
    response = btceapi.getTicker(p, conn)
  File "/Library/Python/2.7/site-packages/btceapi/public.py", line 50, in getTicker
    response = connection.makeJSONRequest("/api/2/%s/ticker" % pair)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 118, in makeJSONRequest
    response = self.makeRequest(url, extra_headers, params)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 112, in makeRequest
    self.conn.request("POST", url, params, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 973, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1001, in _send_request
    self.putrequest(method, url, **skips)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 871, in putrequest
    raise CannotSendRequest()
CannotSendRequest

--------------------------------------------------------------------------------
2014/01/19 19:11:22 - Error while retrieving ltc_eur ticker
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/btcebot/bot.py", line 100, in _ticker_loop
    response = btceapi.getTicker(p, conn)
  File "/Library/Python/2.7/site-packages/btceapi/public.py", line 50, in getTicker
    response = connection.makeJSONRequest("/api/2/%s/ticker" % pair)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 118, in makeJSONRequest
    response = self.makeRequest(url, extra_headers, params)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 112, in makeRequest
    self.conn.request("POST", url, params, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 973, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1007, in _send_request
    self.endheaders(body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 969, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 829, in _send_output
    self.send(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 791, in send
    self.connect()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1172, in connect
    self.timeout, self.source_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 553, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
gaierror: [Errno 8] nodename nor servname provided, or not known

--------------------------------------------------------------------------------
2014/01/19 19:11:22 - Error while retrieving btc_usd ticker
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/btcebot/bot.py", line 100, in _ticker_loop
    response = btceapi.getTicker(p, conn)
  File "/Library/Python/2.7/site-packages/btceapi/public.py", line 50, in getTicker
    response = connection.makeJSONRequest("/api/2/%s/ticker" % pair)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 118, in makeJSONRequest
    response = self.makeRequest(url, extra_headers, params)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 112, in makeRequest
    self.conn.request("POST", url, params, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 973, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1001, in _send_request
    self.putrequest(method, url, **skips)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 871, in putrequest
    raise CannotSendRequest()
CannotSendRequest

--------------------------------------------------------------------------------
2014/01/19 19:11:22 - Error while retrieving ltc_btc ticker
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/btcebot/bot.py", line 100, in _ticker_loop
    response = btceapi.getTicker(p, conn)
  File "/Library/Python/2.7/site-packages/btceapi/public.py", line 50, in getTicker
    response = connection.makeJSONRequest("/api/2/%s/ticker" % pair)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 118, in makeJSONRequest
    response = self.makeRequest(url, extra_headers, params)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 112, in makeRequest
    self.conn.request("POST", url, params, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 973, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1001, in _send_request
    self.putrequest(method, url, **skips)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 871, in putrequest
    raise CannotSendRequest()
CannotSendRequest

--------------------------------------------------------------------------------
2014/01/19 19:11:22 - Error while retrieving ltc_rur ticker
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/btcebot/bot.py", line 100, in _ticker_loop
    response = btceapi.getTicker(p, conn)
  File "/Library/Python/2.7/site-packages/btceapi/public.py", line 50, in getTicker
    response = connection.makeJSONRequest("/api/2/%s/ticker" % pair)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 118, in makeJSONRequest
    response = self.makeRequest(url, extra_headers, params)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 112, in makeRequest
    self.conn.request("POST", url, params, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 973, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1001, in _send_request
    self.putrequest(method, url, **skips)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 871, in putrequest
    raise CannotSendRequest()
CannotSendRequest

--------------------------------------------------------------------------------
2014/01/19 19:11:22 - Error while retrieving ltc_usd ticker
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/btcebot/bot.py", line 100, in _ticker_loop
    response = btceapi.getTicker(p, conn)
  File "/Library/Python/2.7/site-packages/btceapi/public.py", line 50, in getTicker
    response = connection.makeJSONRequest("/api/2/%s/ticker" % pair)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 118, in makeJSONRequest
    response = self.makeRequest(url, extra_headers, params)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 112, in makeRequest
    self.conn.request("POST", url, params, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 973, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1001, in _send_request
    self.putrequest(method, url, **skips)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 871, in putrequest
    raise CannotSendRequest()
CannotSendRequest

--------------------------------------------------------------------------------
2014/01/19 19:11:22 - Error while retrieving btc_eur ticker
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/btcebot/bot.py", line 100, in _ticker_loop
    response = btceapi.getTicker(p, conn)
  File "/Library/Python/2.7/site-packages/btceapi/public.py", line 50, in getTicker
    response = connection.makeJSONRequest("/api/2/%s/ticker" % pair)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 118, in makeJSONRequest
    response = self.makeRequest(url, extra_headers, params)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 112, in makeRequest
    self.conn.request("POST", url, params, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 973, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1001, in _send_request
    self.putrequest(method, url, **skips)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 871, in putrequest
    raise CannotSendRequest()
CannotSendRequest

--------------------------------------------------------------------------------
2014/01/19 19:11:22 - Error while retrieving btc_rur ticker
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/btcebot/bot.py", line 100, in _ticker_loop
    response = btceapi.getTicker(p, conn)
  File "/Library/Python/2.7/site-packages/btceapi/public.py", line 50, in getTicker
    response = connection.makeJSONRequest("/api/2/%s/ticker" % pair)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 118, in makeJSONRequest
    response = self.makeRequest(url, extra_headers, params)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 112, in makeRequest
    self.conn.request("POST", url, params, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 973, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1001, in _send_request
    self.putrequest(method, url, **skips)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 871, in putrequest
    raise CannotSendRequest()
CannotSendRequest

--------------------------------------------------------------------------------
2014/01/19 19:18:10 - Error while retrieving ltc_eur ticker
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/btcebot/bot.py", line 100, in _ticker_loop
    response = btceapi.getTicker(p, conn)
  File "/Library/Python/2.7/site-packages/btceapi/public.py", line 50, in getTicker
    response = connection.makeJSONRequest("/api/2/%s/ticker" % pair)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 118, in makeJSONRequest
    response = self.makeRequest(url, extra_headers, params)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 112, in makeRequest
    self.conn.request("POST", url, params, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 973, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1007, in _send_request
    self.endheaders(body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 969, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 829, in _send_output
    self.send(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 791, in send
    self.connect()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1172, in connect
    self.timeout, self.source_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 553, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
gaierror: [Errno 8] nodename nor servname provided, or not known

--------------------------------------------------------------------------------
2014/01/19 19:18:10 - Error while retrieving btc_usd ticker
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/btcebot/bot.py", line 100, in _ticker_loop
    response = btceapi.getTicker(p, conn)
  File "/Library/Python/2.7/site-packages/btceapi/public.py", line 50, in getTicker
    response = connection.makeJSONRequest("/api/2/%s/ticker" % pair)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 118, in makeJSONRequest
    response = self.makeRequest(url, extra_headers, params)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 112, in makeRequest
    self.conn.request("POST", url, params, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 973, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1001, in _send_request
    self.putrequest(method, url, **skips)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 871, in putrequest
    raise CannotSendRequest()
CannotSendRequest

--------------------------------------------------------------------------------
2014/01/19 19:18:10 - Error while retrieving ltc_btc ticker
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/btcebot/bot.py", line 100, in _ticker_loop
    response = btceapi.getTicker(p, conn)
  File "/Library/Python/2.7/site-packages/btceapi/public.py", line 50, in getTicker
    response = connection.makeJSONRequest("/api/2/%s/ticker" % pair)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 118, in makeJSONRequest
    response = self.makeRequest(url, extra_headers, params)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 112, in makeRequest
    self.conn.request("POST", url, params, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 973, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1001, in _send_request
    self.putrequest(method, url, **skips)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 871, in putrequest
    raise CannotSendRequest()
CannotSendRequest

--------------------------------------------------------------------------------
2014/01/19 19:18:10 - Error while retrieving ltc_rur ticker
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/btcebot/bot.py", line 100, in _ticker_loop
    response = btceapi.getTicker(p, conn)
  File "/Library/Python/2.7/site-packages/btceapi/public.py", line 50, in getTicker
    response = connection.makeJSONRequest("/api/2/%s/ticker" % pair)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 118, in makeJSONRequest
    response = self.makeRequest(url, extra_headers, params)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 112, in makeRequest
    self.conn.request("POST", url, params, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 973, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1001, in _send_request
    self.putrequest(method, url, **skips)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 871, in putrequest
    raise CannotSendRequest()
CannotSendRequest

--------------------------------------------------------------------------------
2014/01/19 19:18:10 - Error while retrieving ltc_usd ticker
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/btcebot/bot.py", line 100, in _ticker_loop
    response = btceapi.getTicker(p, conn)
  File "/Library/Python/2.7/site-packages/btceapi/public.py", line 50, in getTicker
    response = connection.makeJSONRequest("/api/2/%s/ticker" % pair)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 118, in makeJSONRequest
    response = self.makeRequest(url, extra_headers, params)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 112, in makeRequest
    self.conn.request("POST", url, params, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 973, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1001, in _send_request
    self.putrequest(method, url, **skips)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 871, in putrequest
    raise CannotSendRequest()
CannotSendRequest

--------------------------------------------------------------------------------
2014/01/19 19:18:10 - Error while retrieving btc_eur ticker
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/btcebot/bot.py", line 100, in _ticker_loop
    response = btceapi.getTicker(p, conn)
  File "/Library/Python/2.7/site-packages/btceapi/public.py", line 50, in getTicker
    response = connection.makeJSONRequest("/api/2/%s/ticker" % pair)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 118, in makeJSONRequest
    response = self.makeRequest(url, extra_headers, params)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 112, in makeRequest
    self.conn.request("POST", url, params, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 973, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1001, in _send_request
    self.putrequest(method, url, **skips)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 871, in putrequest
    raise CannotSendRequest()
CannotSendRequest

--------------------------------------------------------------------------------
2014/01/19 19:18:10 - Error while retrieving btc_rur ticker
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/btcebot/bot.py", line 100, in _ticker_loop
    response = btceapi.getTicker(p, conn)
  File "/Library/Python/2.7/site-packages/btceapi/public.py", line 50, in getTicker
    response = connection.makeJSONRequest("/api/2/%s/ticker" % pair)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 118, in makeJSONRequest
    response = self.makeRequest(url, extra_headers, params)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 112, in makeRequest
    self.conn.request("POST", url, params, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 973, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1001, in _send_request
    self.putrequest(method, url, **skips)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 871, in putrequest
    raise CannotSendRequest()
CannotSendRequest

--------------------------------------------------------------------------------
2014/01/19 20:08:14 - Error while retrieving ltc_btc ticker
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/btcebot/bot.py", line 100, in _ticker_loop
    response = btceapi.getTicker(p, conn)
  File "/Library/Python/2.7/site-packages/btceapi/public.py", line 50, in getTicker
    response = connection.makeJSONRequest("/api/2/%s/ticker" % pair)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 118, in makeJSONRequest
    response = self.makeRequest(url, extra_headers, params)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 113, in makeRequest
    response = self.conn.getresponse().read()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1045, in getresponse
    response.begin()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 409, in begin
    version, status, reason = self._read_status()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 373, in _read_status
    raise BadStatusLine(line)
BadStatusLine: ''

--------------------------------------------------------------------------------
2014/01/19 20:08:14 - Error while retrieving ltc_rur ticker
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/btcebot/bot.py", line 100, in _ticker_loop
    response = btceapi.getTicker(p, conn)
  File "/Library/Python/2.7/site-packages/btceapi/public.py", line 50, in getTicker
    response = connection.makeJSONRequest("/api/2/%s/ticker" % pair)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 118, in makeJSONRequest
    response = self.makeRequest(url, extra_headers, params)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 112, in makeRequest
    self.conn.request("POST", url, params, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 973, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1001, in _send_request
    self.putrequest(method, url, **skips)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 871, in putrequest
    raise CannotSendRequest()
CannotSendRequest

--------------------------------------------------------------------------------
2014/01/19 20:08:14 - Error while retrieving ltc_usd ticker
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/btcebot/bot.py", line 100, in _ticker_loop
    response = btceapi.getTicker(p, conn)
  File "/Library/Python/2.7/site-packages/btceapi/public.py", line 50, in getTicker
    response = connection.makeJSONRequest("/api/2/%s/ticker" % pair)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 118, in makeJSONRequest
    response = self.makeRequest(url, extra_headers, params)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 112, in makeRequest
    self.conn.request("POST", url, params, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 973, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1001, in _send_request
    self.putrequest(method, url, **skips)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 871, in putrequest
    raise CannotSendRequest()
CannotSendRequest

--------------------------------------------------------------------------------
2014/01/19 20:08:14 - Error while retrieving btc_eur ticker
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/btcebot/bot.py", line 100, in _ticker_loop
    response = btceapi.getTicker(p, conn)
  File "/Library/Python/2.7/site-packages/btceapi/public.py", line 50, in getTicker
    response = connection.makeJSONRequest("/api/2/%s/ticker" % pair)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 118, in makeJSONRequest
    response = self.makeRequest(url, extra_headers, params)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 112, in makeRequest
    self.conn.request("POST", url, params, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 973, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1001, in _send_request
    self.putrequest(method, url, **skips)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 871, in putrequest
    raise CannotSendRequest()
CannotSendRequest

--------------------------------------------------------------------------------
2014/01/19 20:08:14 - Error while retrieving btc_rur ticker
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/btcebot/bot.py", line 100, in _ticker_loop
    response = btceapi.getTicker(p, conn)
  File "/Library/Python/2.7/site-packages/btceapi/public.py", line 50, in getTicker
    response = connection.makeJSONRequest("/api/2/%s/ticker" % pair)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 118, in makeJSONRequest
    response = self.makeRequest(url, extra_headers, params)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 112, in makeRequest
    self.conn.request("POST", url, params, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 973, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1001, in _send_request
    self.putrequest(method, url, **skips)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 871, in putrequest
    raise CannotSendRequest()
CannotSendRequest

--------------------------------------------------------------------------------
2014/01/19 21:11:28 - Error while retrieving ltc_eur ticker
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/btcebot/bot.py", line 100, in _ticker_loop
    response = btceapi.getTicker(p, conn)
  File "/Library/Python/2.7/site-packages/btceapi/public.py", line 50, in getTicker
    response = connection.makeJSONRequest("/api/2/%s/ticker" % pair)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 118, in makeJSONRequest
    response = self.makeRequest(url, extra_headers, params)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 112, in makeRequest
    self.conn.request("POST", url, params, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 973, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1007, in _send_request
    self.endheaders(body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 969, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 829, in _send_output
    self.send(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 791, in send
    self.connect()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1172, in connect
    self.timeout, self.source_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 571, in create_connection
    raise err
error: [Errno 50] Network is down

--------------------------------------------------------------------------------
2014/01/19 21:11:28 - Error while retrieving btc_usd ticker
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/btcebot/bot.py", line 100, in _ticker_loop
    response = btceapi.getTicker(p, conn)
  File "/Library/Python/2.7/site-packages/btceapi/public.py", line 50, in getTicker
    response = connection.makeJSONRequest("/api/2/%s/ticker" % pair)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 118, in makeJSONRequest
    response = self.makeRequest(url, extra_headers, params)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 112, in makeRequest
    self.conn.request("POST", url, params, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 973, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1001, in _send_request
    self.putrequest(method, url, **skips)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 871, in putrequest
    raise CannotSendRequest()
CannotSendRequest

--------------------------------------------------------------------------------
2014/01/19 21:11:28 - Error while retrieving ltc_btc ticker
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/btcebot/bot.py", line 100, in _ticker_loop
    response = btceapi.getTicker(p, conn)
  File "/Library/Python/2.7/site-packages/btceapi/public.py", line 50, in getTicker
    response = connection.makeJSONRequest("/api/2/%s/ticker" % pair)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 118, in makeJSONRequest
    response = self.makeRequest(url, extra_headers, params)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 112, in makeRequest
    self.conn.request("POST", url, params, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 973, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1001, in _send_request
    self.putrequest(method, url, **skips)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 871, in putrequest
    raise CannotSendRequest()
CannotSendRequest

--------------------------------------------------------------------------------
2014/01/19 21:11:28 - Error while retrieving ltc_rur ticker
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/btcebot/bot.py", line 100, in _ticker_loop
    response = btceapi.getTicker(p, conn)
  File "/Library/Python/2.7/site-packages/btceapi/public.py", line 50, in getTicker
    response = connection.makeJSONRequest("/api/2/%s/ticker" % pair)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 118, in makeJSONRequest
    response = self.makeRequest(url, extra_headers, params)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 112, in makeRequest
    self.conn.request("POST", url, params, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 973, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1001, in _send_request
    self.putrequest(method, url, **skips)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 871, in putrequest
    raise CannotSendRequest()
CannotSendRequest

--------------------------------------------------------------------------------
2014/01/19 21:11:28 - Error while retrieving ltc_usd ticker
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/btcebot/bot.py", line 100, in _ticker_loop
    response = btceapi.getTicker(p, conn)
  File "/Library/Python/2.7/site-packages/btceapi/public.py", line 50, in getTicker
    response = connection.makeJSONRequest("/api/2/%s/ticker" % pair)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 118, in makeJSONRequest
    response = self.makeRequest(url, extra_headers, params)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 112, in makeRequest
    self.conn.request("POST", url, params, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 973, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1001, in _send_request
    self.putrequest(method, url, **skips)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 871, in putrequest
    raise CannotSendRequest()
CannotSendRequest

--------------------------------------------------------------------------------
2014/01/19 21:11:28 - Error while retrieving btc_eur ticker
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/btcebot/bot.py", line 100, in _ticker_loop
    response = btceapi.getTicker(p, conn)
  File "/Library/Python/2.7/site-packages/btceapi/public.py", line 50, in getTicker
    response = connection.makeJSONRequest("/api/2/%s/ticker" % pair)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 118, in makeJSONRequest
    response = self.makeRequest(url, extra_headers, params)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 112, in makeRequest
    self.conn.request("POST", url, params, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 973, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1001, in _send_request
    self.putrequest(method, url, **skips)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 871, in putrequest
    raise CannotSendRequest()
CannotSendRequest

--------------------------------------------------------------------------------
2014/01/19 21:11:28 - Error while retrieving btc_rur ticker
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/btcebot/bot.py", line 100, in _ticker_loop
    response = btceapi.getTicker(p, conn)
  File "/Library/Python/2.7/site-packages/btceapi/public.py", line 50, in getTicker
    response = connection.makeJSONRequest("/api/2/%s/ticker" % pair)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 118, in makeJSONRequest
    response = self.makeRequest(url, extra_headers, params)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 112, in makeRequest
    self.conn.request("POST", url, params, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 973, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1001, in _send_request
    self.putrequest(method, url, **skips)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 871, in putrequest
    raise CannotSendRequest()
CannotSendRequest

--------------------------------------------------------------------------------
2014/01/19 21:47:59 - Error while retrieving ltc_eur ticker
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/btcebot/bot.py", line 100, in _ticker_loop
    response = btceapi.getTicker(p, conn)
  File "/Library/Python/2.7/site-packages/btceapi/public.py", line 50, in getTicker
    response = connection.makeJSONRequest("/api/2/%s/ticker" % pair)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 118, in makeJSONRequest
    response = self.makeRequest(url, extra_headers, params)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 112, in makeRequest
    self.conn.request("POST", url, params, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 973, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1007, in _send_request
    self.endheaders(body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 969, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 829, in _send_output
    self.send(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 791, in send
    self.connect()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1172, in connect
    self.timeout, self.source_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 553, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
gaierror: [Errno 8] nodename nor servname provided, or not known

--------------------------------------------------------------------------------
2014/01/19 21:47:59 - Error while retrieving btc_usd ticker
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/btcebot/bot.py", line 100, in _ticker_loop
    response = btceapi.getTicker(p, conn)
  File "/Library/Python/2.7/site-packages/btceapi/public.py", line 50, in getTicker
    response = connection.makeJSONRequest("/api/2/%s/ticker" % pair)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 118, in makeJSONRequest
    response = self.makeRequest(url, extra_headers, params)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 112, in makeRequest
    self.conn.request("POST", url, params, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 973, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1001, in _send_request
    self.putrequest(method, url, **skips)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 871, in putrequest
    raise CannotSendRequest()
CannotSendRequest

--------------------------------------------------------------------------------
2014/01/19 21:47:59 - Error while retrieving ltc_btc ticker
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/btcebot/bot.py", line 100, in _ticker_loop
    response = btceapi.getTicker(p, conn)
  File "/Library/Python/2.7/site-packages/btceapi/public.py", line 50, in getTicker
    response = connection.makeJSONRequest("/api/2/%s/ticker" % pair)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 118, in makeJSONRequest
    response = self.makeRequest(url, extra_headers, params)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 112, in makeRequest
    self.conn.request("POST", url, params, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 973, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1001, in _send_request
    self.putrequest(method, url, **skips)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 871, in putrequest
    raise CannotSendRequest()
CannotSendRequest

--------------------------------------------------------------------------------
2014/01/19 21:47:59 - Error while retrieving ltc_rur ticker
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/btcebot/bot.py", line 100, in _ticker_loop
    response = btceapi.getTicker(p, conn)
  File "/Library/Python/2.7/site-packages/btceapi/public.py", line 50, in getTicker
    response = connection.makeJSONRequest("/api/2/%s/ticker" % pair)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 118, in makeJSONRequest
    response = self.makeRequest(url, extra_headers, params)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 112, in makeRequest
    self.conn.request("POST", url, params, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 973, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1001, in _send_request
    self.putrequest(method, url, **skips)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 871, in putrequest
    raise CannotSendRequest()
CannotSendRequest

--------------------------------------------------------------------------------
2014/01/19 21:47:59 - Error while retrieving ltc_usd ticker
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/btcebot/bot.py", line 100, in _ticker_loop
    response = btceapi.getTicker(p, conn)
  File "/Library/Python/2.7/site-packages/btceapi/public.py", line 50, in getTicker
    response = connection.makeJSONRequest("/api/2/%s/ticker" % pair)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 118, in makeJSONRequest
    response = self.makeRequest(url, extra_headers, params)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 112, in makeRequest
    self.conn.request("POST", url, params, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 973, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1001, in _send_request
    self.putrequest(method, url, **skips)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 871, in putrequest
    raise CannotSendRequest()
CannotSendRequest

--------------------------------------------------------------------------------
2014/01/19 21:47:59 - Error while retrieving btc_eur ticker
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/btcebot/bot.py", line 100, in _ticker_loop
    response = btceapi.getTicker(p, conn)
  File "/Library/Python/2.7/site-packages/btceapi/public.py", line 50, in getTicker
    response = connection.makeJSONRequest("/api/2/%s/ticker" % pair)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 118, in makeJSONRequest
    response = self.makeRequest(url, extra_headers, params)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 112, in makeRequest
    self.conn.request("POST", url, params, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 973, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1001, in _send_request
    self.putrequest(method, url, **skips)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 871, in putrequest
    raise CannotSendRequest()
CannotSendRequest

--------------------------------------------------------------------------------
2014/01/19 21:47:59 - Error while retrieving btc_rur ticker
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/btcebot/bot.py", line 100, in _ticker_loop
    response = btceapi.getTicker(p, conn)
  File "/Library/Python/2.7/site-packages/btceapi/public.py", line 50, in getTicker
    response = connection.makeJSONRequest("/api/2/%s/ticker" % pair)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 118, in makeJSONRequest
    response = self.makeRequest(url, extra_headers, params)
  File "/Library/Python/2.7/site-packages/btceapi/common.py", line 112, in makeRequest
    self.conn.request("POST", url, params, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 973, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1001, in _send_request
    self.putrequest(method, url, **skips)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 871, in putrequest
    raise CannotSendRequest()
CannotSendRequest

--------------------------------------------------------------------------------
